# Generated by Django 3.1 on 2020-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='cow',
            field=models.TextField(default=''),
        ),
    ]
